/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

/* Generated modules for account 0x504b41d0fe4a9424ddc4ddd3517acbfc23f17805e2fb82d5caf8d9fcfeb28a02 */

import { aptos } from "@sentio/sdk";
import { Address, MoveModule } from "aptos-sdk/src/generated";

export namespace weighted_pool_lp_coin {
  export class WeightedPoolToken<T0, T1, T2, T3, T4, T5, T6, T7> {
    static TYPE_QNAME =
      "0x504b41d0fe4a9424ddc4ddd3517acbfc23f17805e2fb82d5caf8d9fcfeb28a02::weighted_pool_lp_coin::WeightedPoolToken";
    dummy_field: Boolean;
  }

  export function loadTypes(_r: aptos.TypeRegistry) {
    loadAllTypes(_r);
  }
  export const ABI: MoveModule = JSON.parse(
    '{"address":"0x504b41d0fe4a9424ddc4ddd3517acbfc23f17805e2fb82d5caf8d9fcfeb28a02","name":"weighted_pool_lp_coin","friends":[],"exposed_functions":[],"structs":[{"name":"WeightedPoolToken","is_native":false,"abilities":[],"generic_type_params":[{"constraints":[]},{"constraints":[]},{"constraints":[]},{"constraints":[]},{"constraints":[]},{"constraints":[]},{"constraints":[]},{"constraints":[]}],"fields":[{"name":"dummy_field","type":"bool"}]}]}'
  );
}

export function loadAllTypes(_r: aptos.TypeRegistry) {
  _r.load(weighted_pool_lp_coin.ABI);
}
