/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

/* Generated modules for account 0x66c2cd54520b51294f62392203ed87de0e7c47b3650f5ed0fbe1578835275b8c */

import {
  MoveCoder,
  AptosBindOptions,
  AptosBaseProcessor,
  TypedEventInstance,
  AptosNetwork,
  TypedEntryFunctionPayload,
  AptosContext,
  CallFilter,
} from "@sentio/sdk-aptos";
import { AptosFetchConfig } from "@sentio/protos";
import { Address, MoveModule } from "aptos-sdk/src/generated";

export namespace stable_pool_lp_coin {
  export class StablePoolToken<T0, T1, T2, T3> {
    static TYPE_QNAME =
      "0x66c2cd54520b51294f62392203ed87de0e7c47b3650f5ed0fbe1578835275b8c::stable_pool_lp_coin::StablePoolToken";
    dummy_field: Boolean;
  }

  export function loadTypes(_r: MoveCoder) {
    loadAllTypes(_r);
  }
  export const ABI: MoveModule = JSON.parse(
    '{"address":"0x66c2cd54520b51294f62392203ed87de0e7c47b3650f5ed0fbe1578835275b8c","name":"stable_pool_lp_coin","friends":[],"exposed_functions":[],"structs":[{"name":"StablePoolToken","is_native":false,"abilities":[],"generic_type_params":[{"constraints":[]},{"constraints":[]},{"constraints":[]},{"constraints":[]}],"fields":[{"name":"dummy_field","type":"bool"}]}]}'
  );
}

export function loadAllTypes(_r: MoveCoder) {
  _r.load(stable_pool_lp_coin.ABI);
}
