/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

/* Generated modules for account 0x385068db10693e06512ed54b1e6e8f1fb9945bb7a78c28a45585939ce953f99e */

import { aptos } from "@sentio/sdk";
import { Address, MoveModule } from "aptos/src/generated";

export namespace lp_coin {
  export class LP<T0, T1, T2> {
    dummy_field: Boolean;
  }

  export function loadTypes(registry: aptos.TypeRegistry) {
    loadAllTypes(registry);
  }
  export const ABI: MoveModule = JSON.parse(
    '{"address":"0x385068db10693e06512ed54b1e6e8f1fb9945bb7a78c28a45585939ce953f99e","name":"lp_coin","friends":[],"exposed_functions":[],"structs":[{"name":"LP","is_native":false,"abilities":[],"generic_type_params":[{"constraints":[]},{"constraints":[]},{"constraints":[]}],"fields":[{"name":"dummy_field","type":"bool"}]}]}'
  );
}

function loadAllTypes(registry: aptos.TypeRegistry) {
  registry.load(lp_coin.ABI);
}
